{{- if .Values.gateway.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: gloo
    gloo: gateway
  name: gateway-conversion
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      gloo: gateway
  template:
    metadata:
      labels:
        gloo: gateway
    spec:
      containers:
        - image: "{{ .Values.gateway.conversionJob.image.repository }}:{{ .Values.gateway.conversionJob.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.conversionJob.image.pullPolicy }}
          name: gateway-conversion
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10101
            capabilities:
              drop:
                - ALL
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
  {{- end }}